version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: store_pmdb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: pmdbstore
    volumes:
      - store_pmdb:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
  api:
    container_name: api_pmdb
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  store_pmdb:
  api_volume:

networks:
  fullstack:
    driver: bridge

# version: '3'
#
# services: 
#   postgres: 
#     image: postgres:latest
#     container_name: pmdb_store
#     ports: 
#       - 5432:5432
#     restart: always
#     environment: 
#       POSTGRES_PASSWORD: postgres123
#       POSTGRES_USER: postgres 
#       POSTGRES_DB: pmdbstore
#     volumes: 
#       - pmdb_store:/var/lib/postgresql/data
#       - ./dbshell:/docker-entrypoint-initdb.d/
#     networks: 
#       - fullstack
#   pmdb_api:
#     container_name: pmdb_api
#     build: .
#     ports: 
#       - 8080:8080
#     restart: always
#     volumes: 
#       - api_volume:/usr/src/app/
#     depends_on: 
#       - postgres
#     networks:
#       - fullstack
#
# volumes: 
#   pmdb_store: 
#   api_volume:
# networks: 
#   fullstack:
#     driver: bridge
